
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 08 12:59:43 EST 2017
//----------------------------------------------------

package bantam.parser;

/** CUP generated class containing symbol constants. */
public class TokenIds {
  /* terminals */
  public static final int DIVIDE = 16;
  public static final int SEMI = 36;
  public static final int LPAREN = 30;
  public static final int DECR = 29;
  public static final int INCR = 28;
  public static final int FOR = 8;
  public static final int MINUS = 14;
  public static final int INSTANCEOF = 12;
  public static final int RPAREN = 31;
  public static final int NOT = 18;
  public static final int AND = 19;
  public static final int LT = 23;
  public static final int OR = 20;
  public static final int COMMA = 37;
  public static final int CLASS = 3;
  public static final int GEQ = 26;
  public static final int PLUS = 13;
  public static final int ASSIGN = 27;
  public static final int IF = 5;
  public static final int LSQBRACE = 34;
  public static final int ID = 39;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int INT_CONST = 40;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int BREAK = 9;
  public static final int EQ = 21;
  public static final int LEX_ERROR = 2;
  public static final int TIMES = 15;
  public static final int LBRACE = 32;
  public static final int ELSE = 6;
  public static final int WHILE = 7;
  public static final int RBRACE = 33;
  public static final int MODULUS = 17;
  public static final int EXTENDS = 4;
  public static final int NE = 22;
  public static final int LEQ = 24;
  public static final int BOOLEAN_CONST = 41;
  public static final int RSQBRACE = 35;
  public static final int STRING_CONST = 42;
  public static final int GT = 25;
}

